{% set name = "AdvancedAnalytics" %}
{% set version = "1.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5c03b62cf1d4c539d6110809800a4f48a28fb5ae1647c32be294daf9405a2967

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python

about:
  home: https://github.com/tandonneur/AdvancedAnalytics
  license: MIT
  license_family: MIT
  license_file: 
  summary: Python support for 'The Art and Science of Data Analytics'
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
